package com.v7878.zygisk.gradle.tasks;

import static com.v7878.zygisk.gradle.Utils.files;

import org.gradle.api.DefaultTask;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.tasks.InputFiles;
import org.gradle.api.tasks.OutputFile;
import org.gradle.api.tasks.TaskAction;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.TreeMap;

public abstract class ChecksumTask extends DefaultTask {
    private static final String HEADER = """
            # Generated by ZygoteLoader. DO NOT EDIT.
            
            ui_print "- Verify module resources"
            
            function do_verify() {
                [ -f "$MODPATH/$1" ] || abort "! Module resource '$1' not found"
                (echo "$2  $MODPATH/$1" | sha256sum -c -s -) || abort "! Module resource '$1' verify failed"
                ui_print "  '$1' verified"
            }
            """;
    private static final String TAIL = "unset -f do_verify";

    private static String checksum(Path path) {
        try {
            MessageDigest sha256 = MessageDigest.getInstance("SHA-256");

            OutputStream stream = new OutputStream() {
                @Override
                public void write(int i) throws IOException {
                    this.write(new byte[]{(byte) i});
                }

                @Override
                public void write(byte[] b, int off, int len) {
                    sha256.update(b, off, len);
                }
            };

            Files.copy(path, stream);

            StringBuilder sb = new StringBuilder();
            for (byte b : sha256.digest()) {
                sb.append(String.format("%02x", b & 0xff));
            }
            return sb.toString();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @InputFiles
    public abstract ConfigurableFileCollection getSourceDirectory();

    @OutputFile
    public abstract RegularFileProperty getDestinationFile();

    @TaskAction
    public void doAction() throws Exception {
        var checksums = new TreeMap<String, String>();

        getSourceDirectory().getAsFileTree().visit(files(file -> {
            var path = file.getPath();
            if (!path.startsWith("META-INF")) {
                path = path.replace("\\", "/");
                checksums.put(path, checksum(file.getFile().toPath()));
            }
        }));

        StringBuilder sb = new StringBuilder();
        sb.append(HEADER).append("\n\n");

        for (var checksum : checksums.entrySet()) {
            sb.append("do_verify ")
                    .append(checksum.getKey())
                    .append(" ")
                    .append(checksum.getValue())
                    .append('\n');
        }

        sb.append("\n\n").append(TAIL);

        Files.writeString(getDestinationFile().getAsFile().get().toPath(), sb);
    }
}
